system:
  user: 'labhacker'
colab:
  dir: '/opt/colab'
  branch: 'master'
  repository: 'https://github.com/labhackercd/edemocracia-colab.git'
  virtualenv: '/opt/colab-env'
  email_from: '"Portal e-Democracia" <edemocracia@camara.leg.br>'
  server_email: '"Portal e-Democracia" <edemocracia@camara.leg.br>'
  email_subject_prefix: '[e-Democracia]'
  email_host: '200.219.133.2'
  email_port: '25'
  email_use_tls: 'False'
  email_address: 'edemocracia@camara.leg.br'
  email_password: ''
  allowed_hosts:
    - '200.219.134.68'
    - '200.219.134.77'
    - 'beta.edemocracia.camara.leg.br'
    - 'beta.edemocracia.camara.gov.br'
    - 'edemocracia.labhackercd.net'
  site_url: 'http://edemocracia.labhackercd.net'
  plugins_dir: '/opt/colab-plugins'
  admins:
    - ["Admin", "edemocracia@camara.leg.br"]
  google_oauth_key: ''
  google_oauth_secret: ''
  facebook_oauth_key: ''
  facebook_oauth_secret: ''
wikilegis:
  dir: '/opt/wikilegis'
  branch: 'colab_integration'
  repository: 'https://github.com/labhackercd/wikilegis.git'
  virtualenv: '/opt/wikilegis-env'
  email_host: '200.219.133.2'
  email_port: '25'
  email_use_tls: 'False'
  email_from: '"Portal e-Democracia[Wikilegis]" <wikilegis@camara.leg.br>'
  email_address: 'wikilegis@camara.leg.br'
  email_password: ''
  url_prefix: '/wikilegis'
discourse:
  dir: '/opt/discourse'
  rbenv: '/opt/rbenv/'
  branch: 'master'
  notification_email: 'edemocracia@camara.leg.br'
  logo_url: '/static/img/logo-expressao-horizontal.png'
  small_logo_url: '/static/img/logo-expressao-horizontal.png'
  fav_icon_url: '/static/img/favicon/favicon-32x32.png'
  repository: 'https://github.com/labhackercd/lab-discourse.git'
  hostname: 'beta.edemocracia.camara.leg.br/discourse'
plugins:
  -
    name: 'wikilegis'
    url: 'https://github.com/labhackercd/colab-wikilegis-plugin.git'
    branch: 'master'
  -
    name: 'discourse'
    url: 'https://github.com/labhackercd/colab-discourse-plugin.git'
    branch: 'master'
  -
    name: 'edemocracia'
    url: 'https://github.com/labhackercd/colab-edemocracia-plugin.git'
    branch: 'master'
