system:
  user: 'vagrant'
colab:
  dir: '/opt/colab'
  branch: 'master'
  repository: 'https://github.com/labhackercd/edemocracia-colab.git'
  virtualenv: '/opt/virtualenvs/colab'
  email_from: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  server_email: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  email_subject_prefix: '[e-Democracia]'
  external_hostname: 'edemocracia.dev'
  admins:
    - ["Admin", "admin@email.com"]
wikilegis:
  dir: '/opt/wikilegis'
discourse:
  dir: '/opt/discourse'
  branch: 'master'
  repository: 'https://github.com/labhackercd/lab-discourse.git'
