system:
  user: 'edemocracia'
colab:
  dir: '/opt/colab'
  branch: 'master'
  repository: 'https://github.com/labhackercd/edemocracia-colab.git'
  virtualenv: '/opt/virtualenvs/colab'
  email_from: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  server_email: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  email_subject_prefix: '[e-Democracia]'
  email_host: ''
  email_port: 25
  email_use_tls: 'False'
  email_address: ''
  email_password: ''
  allowed_hosts:
    - 'edemocracia.dev'
    - '192.168.66.10'
  site_url: 'http://edemocracia.dev'
  plugins_dir: '/opt/colab-plugins'
  admins:
    - ["Admin", "admin@email.com"]
  google_oauth_key: ''
  google_oauth_secret: ''
  facebook_oauth_key: ''
  facebook_oauth_secret: ''
wikilegis:
  dir: '/opt/wikilegis'
  branch: 'colab_integration'
  repository: 'https://github.com/labhackercd/wikilegis.git'
  virtualenv: '/opt/virtualenvs/wikilegis'
  email_host: ''
  email_use_tls: 'False'
  email_from: '"Portal e-Democracia[Wikilegis]" <email@email.com>'
  email_port: 25
  email_address: ''
  email_password: ''
  url_prefix: '/wikilegis'
  login_url: '/home'
discourse:
  dir: '/opt/discourse'
  rbenv: '/opt/rbenv/'
  branch: 'master'
  notification_email: 'email@email.com'
  logo_url: '/discourse/assets/logo.png'
  small_logo_url: '/discourse/assets/small-logo.png'
  fav_icon_url: '/discourse/assets/fav_icon.png'
  repository: 'https://github.com/labhackercd/lab-discourse.git'
audiencias:
  dir: '/opt/audiencias'
  branch: 'master'
  repository: 'https://github.com/labhackercd/audiencias-publicas.git'
  virtualenv: '/opt/virtualenvs/audiencias'
  email_host: ''
  email_port: 25
  email_use_tls: 'False'
  email_from: '"Portal e-Democracia[audiencias]" <email@email.com>'
  email_address: ''
  email_password: ''
  url_prefix: '/audiencias'
  login_url: '/home'
  youtube_api_key: ''
  youtube_channel_id: 'UC-ZkSRh-7UEuwXJQ9UMCFJA'
  youtube_search_query: 'audiência pública'
plugins:
  -
    name: 'wikilegis'
    url: 'https://github.com/labhackercd/colab-wikilegis-plugin.git'
    branch: 'master'
  -
    name: 'discourse'
    url: 'https://github.com/labhackercd/colab-discourse-plugin.git'
    branch: 'master'
  -
    name: 'audiencias'
    url: 'https://github.com/labhackercd/colab-audiencias-plugin.git'
    branch: 'master'
  -
    name: 'edemocracia'
    url: 'https://github.com/labhackercd/colab-edemocracia-plugin.git'
    branch: 'master'
