system:
  user: 'edemocracia'
colab:
  dir: '/opt/colab'
  branch: 'master'
  repository: 'https://github.com/labhackercd/edemocracia-colab.git'
  virtualenv: '/opt/virtualenvs/colab'
  email_from: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  server_email: '"Portal e-Democracia" <portal@edemocracia.gov.br>'
  email_subject_prefix: '[e-Democracia]'
  allowed_hosts:
    - 'edemocracia.dev'
    - '192.168.0.101'
  site_url: 'http://edemocracia.dev'
  plugins_dir: '/opt/colab-plugins'
  admins:
    - ["Admin", "admin@email.com"]
wikilegis:
  dir: '/opt/wikilegis'
  branch: 'colab_integration'
  repository: 'https://github.com/labhackercd/wikilegis.git'
  virtualenv: '/opt/virtualenvs/wikilegis'
  email_host: 'smtp.email.com'
  email_port: '587'
  email_address: 'email@email.com'
  email_password: 'email_pass'
  url_prefix: '/wikilegis'
discourse:
  dir: '/opt/discourse'
  rbenv: '/opt/rbenv/'
  branch: 'master'
  notification_email: 'email@email.com'
  logo_url: '/images/logo.png'
  small_logo_url: '/images/small-logo.png'
  fav_icon_url: '/images/fav_icon.png'
  repository: 'https://github.com/labhackercd/lab-discourse.git'
plugins:
  -
    name: 'wikilegis'
    url: 'https://github.com/labhackercd/colab-wikilegis-plugin.git'
    branch: 'master'
  -
    name: 'discourse'
    url: 'https://github.com/labhackercd/colab-discourse-plugin.git'
    branch: 'master'
  -
    name: 'edemocracia'
    url: 'https://github.com/labhackercd/colab-edemocracia-plugin.git'
    branch: 'master'